print('----CALCULADORA DE TABUADA----')
Valor = int(input('DIGITE O VALOR DESEJADO: '))
print(f'{Valor} * 01 = {Valor*1}')
print(f'{Valor} * 02 = {Valor*2}')
print(f'{Valor} * 03 = {Valor*3}')
print(f'{Valor} * 04 = {Valor*4}')
print(f'{Valor} * 05 = {Valor*5}')
print(f'{Valor} * 06 = {Valor*6}')
print(f'{Valor} * 07 = {Valor*7}')
print(f'{Valor} * 08 = {Valor*8}')
print(f'{Valor} * 09 = {Valor*9}')
print(f'{Valor} * 10 = {Valor*10}')