dados1 = list()
dados2 = list()
dados3 = list()
Linha1 = list()
Linha2 = list()
Linha3 = list()
for c in range(0,3):
    dados1.append(int(input(f"Digite um valor para [0, {c}]: ")))
    Linha1.append(dados1[:])
    dados1.clear()
for c in range(0,3):
    dados2.append(int(input(f"Digite um valor para [1, {c}]: ")))
    Linha2.append(dados2[:])
    dados2.clear()
for c in range(0,3):
    dados3.append(int(input(f"Digite um valor para [2, {c}]: ")))
    Linha3.append(dados3[:])
    dados3.clear()
print(f'  {Linha1[0]}     {Linha1[1]}     {Linha1[2]}  ')
print(f'  {Linha2[0]}     {Linha2[1]}     {Linha2[2]}  ')
print(f'  {Linha3[0]}     {Linha3[1]}     {Linha3[2]}  ')
